export const ADD_WORKOUT_TYPE_START = "ADD_WORKOUT_TYPE_START"
export const ADD_WORKOUT_TYPE = "ADD_WORKOUT_TYPE"
export const ADD_WORKOUT_TYPE_SUCCESS = "ADD_WORKOUT_TYPE_SUCCESS"
export const ADD_WORKOUT_TYPE_FAILURE = "ADD_WORKOUT_TYPE_Failure"
export const ADD_WORKOUT_TYPE_INIT = "ADD_WORKOUT_TYPE_INIT"

export const SHOW_WORKOUT_TYPES_START   = "SHOW_WORKOUT_TYPES_START"
export const SHOW_WORKOUT_TYPES         = "SHOW_WORKOUT_TYPES"
export const SHOW_WORKOUT_TYPES_SUCCESS = "SHOW_WORKOUT_TYPES_SUCCESS"
export const SHOW_WORKOUT_TYPES_FAILURE = "SHOW_WORKOUT_TYPES_FAILURE"


export const UPDATE_COUNT_START = "UPDATE_COUNT_START"
export const UPDATE_COUNT = "UPDATE_COUNT"
export const UPDATE_COUNT_SUCCESS = "UPDATE_COUNT_SUCCESS"
export const UPDATE_COUNT_FAILURE = "UPDATE_COUNT_FAILURE"

export const AUTH_START = "AUTH_START"
export const AUTH = "AUTH"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILURE = "AUTH_FAILURE"
export const AUTH_CHECK = "AUTH_CHECK"
export const LOGOUT = "LOGOUT"